#!/usr/bin/env bash
# configure Nginx to redirect `/redirect_me` to another page
sed -i "s|^}$|\n\tlocation /redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}\n}|" /etc/nginx/sites-available/default
service nginx reload
