#!/usr/bin/env bash
# configure Nginx to redirect `/redirect_me` to another page
apt-get update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
sed -i "s|^}$|\n\tlocation /redirect_me {return 301 /;}\n}|" /etc/nginx/sites-available/default
sed -i "s|^}$|\n\tlocation @404 {return 404 \"Ceci n'est pas une page\";}\n}|" /etc/nginx/sites-available/default
sed -i "s/=404/@404/g" /etc/nginx/sites-available/default
service nginx start
