#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
wget https://github.com/zaynOm/alx-system_engineering-devops/blob/master/0x0C-web_server/1-install_nginx_web_server
source 1-install_nginx_web_server
conf="/etc/nginx/sites-available/default"
sudo sed -i "s|^}$|\n\tlocation /redirect_me {return 301 /;}\n}|" $conf
sudo sed -i "s|^}$|\n\tlocation @404 {return 404 \"Ceci n'est pas une page\";}\n}|" $conf
sudo sed -i "s/=404/@404/g" $conf
sudo sed -i "0,/location \/ {/s/location \/ {/&\n\t\tadd_header X-Served-By '$hostname';/" $config
sudo service nginx restart
