#!/usr/bin/env bash
# install & configure an HAproxy
apt-get update
apt-get -y install haproxy
echo "
	listen myservers
		bind *:80
		server 379715-web-01 100.25.211.211:80 check
		server 379715-web-02 100.25.196.119:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
