#!/usr/bin/env bash
# This script Creates the file /var/run/myscript.pid containing its PID
# displays `To infinity and beyond` indefinitely
# Displays `I hate the kill command` when receiving a SIGTERM signal
# Displays `Y U no love me?!` when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when
# receiving a SIGQUIT or SIGTERM signal.

terminat() {
	sudo rm /var/run/myscript.pid
	exit
}

sudo sh -c 'echo "$$" > /var/run/myscript.pid'

trap 'echo I hate the kill command; terminat' TERM
trap "echo Y U no love me?!" INT
trap "terminat" QUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
