#!/usr/bin/env bash
# This script displays `To infinity and beyond indefinitely`,
# and when receiving a SIGTERM signal it prints `I am invincible!!!`

while true; do
	echo "To infinity and beyond indefinitely"
	sleep 2
	trap 'echo I am invincible!!!' TERM
done
