#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.

while IFS=: read -r un pw id gid info dir sh; do
	echo "The user $un is part of the $gid gang,"\
		"lives in $dir and rides $sh."\
		"$id's place is protected by the passcode $pw,"\
		"more info about the user here: $info"
done < "/etc/passwd"
