#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code
# and displays them ordered from the greatest to the lowest number of occurrences

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
