#!/usr/bin/env bash
# This script displays "Best School" 10 times, and "Hi" after the 9th iteration.

i=0

while [ $i -lt 10 ]; do
	if [ $i -eq 9 ]; then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
