#!/usr/bin/env bash
# This script displays the time fot 12 hours and 59 minutes.

hour=0

while [ $hour -le 12 ]; do
	minute=1
	echo "Hour: $hour"
	((hour++))
	while [ $minute -le 59 ]; do
		echo $minute
		((minute++))
	done
done
