#!/usr/bin/env bash
# 7 lines of less
sed -i 's/^#user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i '/^\tlisten /s/80/8080/' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
